- name: Install OpenJDK 11
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Install OpenJDK 11 on Debian/Ubuntu
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

    - name: Install OpenJDK 11 on Red Hat/CentOS
      yum:
        name: java-1.11.0-openjdk
        state: present
      when: ansible_os_family == 'RedHat'
